function broadcastTrial(in, r, dt, isRunning)
	% BROADCASTTRIAL Sends trial and session telemetry to the broadcast server.
	%   BROADCASTTRIAL(IN, R, DT, ISRUNNING) packages trial performance metrics,
	%   timing information, and session metadata into a structure and transmits
	%   it using the broadcast interface stored in R.
	arguments (Input)
		in struct
		r struct
		dt touchData
		isRunning logical = false
	end

	r.broadcast.send(struct('task',in.task,'name',in.name,'is_running',isRunning,...
		'loop_id',r.loopN,'trial_id',r.trialN,...
		'rewards',dt.data.rewards, ...
		'correct_rate_last10', r.correctRateRecent, 'correct_rate', r.correctRate,...
		'result', r.result, 'reaction_time', r.reactionTime, 'phase', r.phase,...
		'random_rewards',dt.data.random,...
		'start_time',r.startTime,'end_time',r.endTime,...
		'now', string(datetime('now')),...
		'session_id',r.alyxPath,'hostname',r.hostname,'version',r.version,...
		'comment',r.comments(end),...
		'session', in.session.sessionURL));
end