function broadcastTrial(in, r, dt, isRunning)
arguments (Input)
	in struct
	r struct
	dt touchData
	isRunning logical = false
end

r.broadcast.send(struct('task',in.task,'name',in.name,'is_running',isRunning,...
		'loop_id',r.loopN,'trial_id',r.trialN,...
		'correct_rate', r.correctRate,'rewards',dt.data.rewards,...
		'result', r.result, 'reaction_time', r.reactionTime, 'phase', r.phase,...
		'correct_rate_last10', r.correctRateRecent, 'random_rewards',dt.data.random,...
		'start_time',r.startTime,'end_time',r.endTime,...
		'session_id',r.alyxPath,'hostname',r.hostname));
end